### ISSUE TITLE
<html> Needs update?

### ISSUE THREAD

**Issue by dragonfire535** [fojas/cleverbot-node#25]
All messages are responding with "html". Does cleverbot-node need an update?

**Comment by fojas** [comment]
What version are you currently running? `npm view cleverbot-node version` should tell you. The latest version is 0.2.6 and I am not seeing any issues on my requests.

**Comment by dumptyd** [comment]
I was using 0.2.2 🤦‍♂️

**Comment by dragonfire535** [comment]
I've been using 0.2.6.

**Comment by fojas** [comment]
@dragonfire535 Do you mind posting some sample code? Version 0.2.1 had an interface change that required everything to be wrapped in 'prepare'.

**Comment by dragonfire535** [comment]
@fojas I'm using yumabot-core. It's a discord bot framework.

**Comment by fojas** [comment]
I'm assuming this is the project? https://github.com/TheVexatious/YumaBot-Core/

According to the `package.json` in that project, they are using a fork of this package. The fork can be found at https://github.com/briantanner/cleverbot-node

**Comment by TheVexatious** [comment]
@dragonfire535 This is the developer of yumabot-core here, yes as fojas said, that framework wasn't using this repo at the time, because at that time there was a bug that made it respond with "\<html>" every time, so that fork was created to patch it, but now it's fixed i guess, i updated the `package.json` in my repo nowso it should be good, sorry for the inconvenience

**Comment by fojas** [comment]
Thanks so much.
