### ISSUE TITLE
<html> response in linux server

### ISSUE THREAD

**Issue by llool** [fojas/cleverbot-node#31]
So as per example I integrated the cleverbot in my code as below:

    var Cleverbot = require('cleverbot-node');
    cleverbot = new Cleverbot;
    cleverbot.configure({botapi: "KEY"});
    cleverbot.write(cleverMessage, function (response) {
       console.log(response.message);
    });

Running the above from my windows pc, works just fine, but from the linux server, responds as `<html>`

`npm view cleverbot-node version` -> 0.3.3

**Comment by Carbowix** [comment]
yes me to. Can you help?

**Comment by MightyAlex200** [comment]
I am also having this problem, the full response is as follows:

````
{ message: '<html>',
  sessionid: '\n<head><title>401 Authorization Required</title></head>',
  logurl: '\n<body bgcolor="white">',
  vText8: '\n<center><h1>401 Authorization Required</h1></center>',
  vText7: '\n<hr><center>nginx/1.6.2 (Ubuntu)</center>',
  vText6: '\n</body>',
  vText5: '\n</html>',
  vText4: '\n' }
````

**Comment by fojas** [comment]
@MightyAlex200 These all appear to be errors with the 0.2.x versions. Since 0.2.x versions deal with the unofficial Cleverbot API, I am not going to support it. You will need to update to the 0.3.x version (0.3.3 being the latest) and get an API key from here, https://www.cleverbot.com/api/.

@llool are you sure you are using 0.3.3? What version is listed in `node_modules/cleverbot-node/package.json`?

**Comment by WhiteKitty00** [comment]
Hey uhm, I'm having issues update cleverbot-node, it still keeps saying its version 0.2.4.

**Comment by fojas** [comment]
@WhiteKitty00 What does the package.json look like for you app? Is cleverbot-node included in there or is it a dependency of another package?

**Comment by WhiteKitty00** [comment]
@fojas it was cleverbot-node version 0.2.4, I also did npm update in the main folder, and npm update -g, which ran through, but didnt update it, I think npm was bugged for me, because when I did "npm list cleverbot-node" it didnt list it, yet it was registered in the folder, so I reinstalled it, now its version 0.3.3. Sorry for the incident! (My linux server keeps bugging alot recently..)
